language: python

python:
 - "3.12"
 - "3.13"

install:
 - pip install --upgrade pip
 - pip install setuptools wheel
 - pip install -r requirements.txt

script:
 - python setup.py sdist bdist_wheel

notifications:
  slack: just6fun:Eh0j5aOJi6d7bgPzRuZNd7JO
